### ISSUE TITLE
[Bug] Invalid images return with the content-type image/.tmp

### ISSUE THREAD

**Issue by Syer10** [Suwayomi/Suwayomi-Server#129]
## Device information
- Tachidesk version: 0.4.2
- Server Operating System: Windows 10
- Server Desktop Environment: Windows 10
- Server JVM version: OpenJdk 15
- Client Operating System: Windows 10
- Client Web Browser: TachideskJUI

## Steps to reproduce
1. Open Dynasty-Issues Source from Dynasty Extension
2. Click broken manga such as Nico Nico Yuri Hime

### Expected behavior
Request should return 404 or similar error with no content-type header

### Actual behavior
Request returns invalid content with a header `image/.tmp`

## Other details
The same header is also used for covers that were made with 0.4.1 and below, but they return valid images in the content

**Comment by Syer10** [comment]
Just tested it a bit more, it also seems to happen on every second load of a image

**Comment by AriaMoradi** [comment]
This issue was fixed (#100), your cached images are saved with `.tmp` extension which in turn `CachedImageRequest` returns the same. delete your image cache and it'll be fixed, although it returning patterns like  `image/.jpeg` and `image/.png` is wrong and also fixed that in a29010e0d7030b03976f888a8b361db78a79a42a

**Comment by AriaMoradi** [comment]
request for thumbnail of `Nico Nico Yuri Hime Oct. 2014` returns a `text/html` content response which breaks Tachidesk on windows and linux. On windows, renaming the `.tmp` file will fail and on linux files like `17.html; charset=utf-8` are created

**Comment by AriaMoradi** [comment]
does this issue still persist?

**Comment by Syer10** [comment]
Yes

**Comment by AriaMoradi** [comment]
this was fixed in #100, opening another issue for https://github.com/Suwayomi/Tachidesk-Server/issues/129#issuecomment-854504427

**Comment by Farzout** [comment]
it did not fix my problem with deleting cashe or temp folder on windows

Edit: my problem was fixed clearing my browser cache thx

**Comment by Robonau** [comment]
> it did not fix my problem with deleting cashe or temp folder on windows

please make a new issue rather than commenting on an issue fixed and closed 3 years ago
