### ISSUE TITLE
New builds throws exception in ubuntu

### ISSUE THREAD

**Issue by arbuilder** [Suwayomi/Suwayomi-Server#19]
using below command on ubuntu 20.04 (WSL2) gives _Exception in thread "main" java.io.IOException: Current OS and desktop configuration does not support browsing for a URL_

java -jar Tachidesk-v0.2.0-r184.jar

![Screenshot 2021-02-13 233717](https://user-images.githubusercontent.com/78140816/107858171-d4b8f280-6e58-11eb-97c2-c6daf475205a.png)

Earlier non windows specific build were working on ubuntu

**Comment by arbuilder** [comment]
new windows jar build don't work in docker so we should remove the docker info for now

**Comment by AriaMoradi** [comment]
This bug most likely comes from `drokbox.util` and should be fixed upstream.

**Comment by AriaMoradi** [comment]
does the program crash after running under wsl or does it continue working?

**Comment by arbuilder** [comment]
it hangs in extensions i.e. wait , so web ui works but we cant do anything. i have rebuild jar (Tachidesk-v0.2.2-r222.jar) it still show the above error _Exception in thread "main" java.io.IOException: Current OS and desktop configuration does not support browsing for a URL_ but it works on docker (Tachidesk-v0.2.2-r222.jar still hangs on wsl2).

**Summary**
<table>
 <thead>
  <tr>
   <th>S.No.</th><th>jar</th><th>Win 10</th><th>Docker Win 10</th><th>WSL2 Ubuntu 20.04</th>
  </tr>
 </thead>
 <tbody>
  <tr>
   <td>1</td><td>Tachidesk-v0.2.2-r214.jar (latest release github) </td><td>works </td><td>hangs </td><td>hangs</td>
  </tr>
  <tr>
   <td>2</td><td>Tachidesk-v0.2.2-r222.jar (rebuild on my pc) </td><td>works </td><td>works</td><td>hangs</td>
  </tr>
 </tbody>
</table>

**Comment by univeous** [comment]
This also happens on my CentOS Linux server. Can SystemTray be disabled in a system that has no GUI?

**Comment by AriaMoradi** [comment]
Release `v0.2.3` should prevent from crashing on headless systems

**Comment by univeous** [comment]
> Release `v0.2.3` should prevent from crashing on headless systems

I'm using V0.2.3, it seems it will still crash:

![image](https://user-images.githubusercontent.com/40604180/108987494-536e2500-76ce-11eb-8cfa-72773a3faed8.png)

Also, it hangs in extensions i.e. wait.

**Comment by arbuilder** [comment]
> > Release `v0.2.3` should prevent from crashing on headless systems
> 
> I'm using V0.2.3, it seems it will still crash:
> 
> ![image](https://user-images.githubusercontent.com/40604180/108987494-536e2500-76ce-11eb-8cfa-72773a3faed8.png)

check if http://localhost:4567/extensions works and shows extensions if it does then u can ignore this error

**Comment by univeous** [comment]
> > > Release `v0.2.3` should prevent from crashing on headless systems
> > 
> > 
> > I'm using V0.2.3, it seems it will still crash:
> > ![image](https://user-images.githubusercontent.com/40604180/108987494-536e2500-76ce-11eb-8cfa-72773a3faed8.png)
> 
> check if http://localhost:4567/extensions works and shows extensions if it does then u can ignore this error

Library hangs on 'loading...', extensions  and sources hang on 'wait'

**Comment by arbuilder** [comment]
> Library hangs on 'loading...', extensions and sources hang on 'wait'

i see i have the same error in wsl2 , can u run `java -version` and paste the output meanwhile if u have docker u can run `docker run -p 127.0.0.1:4567:4567 docker.io/arbuild/tachidesk-docker` as docker build works with v0.2.3

**Comment by univeous** [comment]
> > Library hangs on 'loading...', extensions and sources hang on 'wait'
> 
> i see i have the same error in wsl2 , can u run `java -version` and paste the output meanwhile if u have docker u can run `docker run -p 127.0.0.1:4567:4567 docker.io/arbuild/tachidesk-docker` as docker build works with v0.2.3

Here is my java version:
![image](https://user-images.githubusercontent.com/40604180/108990923-6c78d500-76d2-11eb-8b34-0629cb6fb656.png)

I tried to run it in docker but still no luck. I will check if it's my network problem.

**Comment by AriaMoradi** [comment]
I tried the app with my archlinux in headless mode and it worked, I can load the `webUI` from my phone but none of the api works because it's trying to connect to the server at `http://127.0.0.1:4567` but my phone sees the server from `http://192.168.1.115`
Maybe @univeous is facing the same issue?

![image](https://user-images.githubusercontent.com/8719233/108992481-9fa96d00-76ae-11eb-832e-1c3ffc2fe30d.png)
![image](https://user-images.githubusercontent.com/8719233/108992470-9cae7c80-76ae-11eb-9cf0-e8ae4d920bb7.png)


Mind you that the app crashing means it getting terminated not printing java exceptions...

**Comment by univeous** [comment]
@AriaMoradi 
Yes, I have the same problem, I just found it.

**Comment by AriaMoradi** [comment]
> I can load the webUI from my phone but none of the api works because it's trying to connect to the server at http://127.0.0.1:4567 but my phone sees the server from http://192.168.1.115

If you are accessing the server from a remote client, To fix this issue you have to map the server's port to your local port with a tunneling program.(One easy to use solution is ssh port forwarding.)

This issue is not a bug, but is so by design, and is to prevent you from running on a remote client. 
Reason being It's a bad idea to run Tachidesk remotely, because it has zero security and the app might break if api calls take a long time to resolve, but if you want to circumvent this limitation you are free to do so.

If you think this limitation should be removed, react to this comment with the rocket emoji, if it gets enough reactions I'll consider doing something about it.

**Comment by arbuilder** [comment]
>  tried the app with my archlinux in headless mode and it worked, I can load the webUI from my phone but none of the api works because it's trying to connect to the server at http://127.0.0.1:4567 but my phone sees the server from http://192.168.1.115
Maybe @univeous is facing the same issue?

yes and that's why it failed on wsl2 also and works on docker because i am exposing docker container port on localhost. 

>If you are accessing the server from a remote client, To fix this issue you have to map the server's port to your local port with a tunneling program.
This issue is not a bug, but is so by design, and is to prevent you from running on a remote client.
Reason being It's a bad idea to run Tachidesk remotely, because it has zero security and the app might break if api calls take a long time to resolve, but if you want to circumvent this limitation you are free to do so.(One easy to use solution is ssh port forwarding.)

i see it also means that using docker will also cause the same issue when using lan ips http://192.168.1.115:4567 and the docker will also not work without port forwarding on headless servers. I will check if i can add forwarding in docker container without breaking the app.

**Comment by arbuilder** [comment]
closing the issues as it is not a bug
